# Site settings
title:       Jakub WÄ™grzynowski
email:       your_email@example.com
author:      Jakub Florian
description: "Copywriter"
baseurl:     ""
url:         "https://jakub-florian.github.io"
date_format: "%b %-d, %Y"
header_pages: 
  - notatki.md


avatar: "/assets/img/awatar.png"

# Social icons
github_username: "Jakub-Florian"

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
sass:
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - screenshot.png
  - vendor
